name: GitHub Actions Demo
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@2ee7edf74b58a6fd41353789e6bfbff4601c478b
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: ${{ github.event.pull_request.head.sha }}
