name: GitHub Actions Demo
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: prbranch
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@44e25d9589451edf6e696f7f3447351b71e5462e
        with:
          path: ./prbranch
          base: ${{ github.event.repository.default_branch }}
          head: ${{ github.event.pull_request.head.sha }}
