name: GitHub Actions Demo
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.3.3
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
