name: GitHub Actions Demo
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: prbranch
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@ce1dde4c36d9195c1c4b508bee4b0e0814e940fe
        with:
          path: ./prbranch
          base: ${{ github.event.repository.default_branch }}
          head: ${{ github.event.pull_request.head.sha }}
